version: "3.1"
services:

  web:
    image: fajarkarim/web-custom
    ports: 
      - "8080:80"
    networks:
      - "int-net"
    depends_on: 
      - mysql
  
  pma:
    image: fajarkarim/pma-custom
    ports:
      - "8081:80"
    networks:
      - "proxy-net"
      - "int-net"
    depends_on: 
      - mysql
    environment:
      - PMA_HOST=mysql

  mysql: 
    image: fajarkarim/mysql-custom
    environment: 
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dbkuasai
      - MYSQL_USER=cilsykuasaiuser
      - MYSQL_PASSWORD=cilsykuasaipassword
      - MYSQL_HOST=mysql
    networks:
        - "int-net"
  
networks: 
  int-net:
  proxy-net: