version: "3.1"
services:
  mysql: 
    image: fajarkarim/mysql-custom
    environment: 
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dbkuasai
      - MYSQL_USER=cilsykuasaiuser
      - MYSQL_PASSWORD=cilsykuasaipassword
      - MYSQL_HOST=mysql
    networks:
        - "int-net"
  
  web:
    image: fajarkarim/web-custom
    ports: 
      - "8080:80"
    networks:
      - "int-net"
    depends_on: 
      - mysql
  
networks: 
  int-net: